# Generated by Django 5.2.17 on 2026-08-13

import django.db.models.deletion
import uuid
import walkie_dokie.contract_intelligence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("kind", models.CharField(choices=[("contract", "合同"), ("price_list", "价目表"), ("attachment", "附件")], max_length=30)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "逻辑文档", "verbose_name_plural": "逻辑文档", "ordering": ("project__name", "name")},
        ),
        migrations.CreateModel(
            name="IndexBuild",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("status", models.CharField(choices=[("draft", "草稿"), ("ready", "可发布"), ("published", "已发布"), ("retired", "已退役"), ("failed", "失败")], default="draft", max_length=20)),
                ("parser_configuration", models.JSONField(default=dict)),
                ("retrieval_configuration", models.JSONField(default=dict)),
                ("evidence_manifest_sha256", models.CharField(blank=True, max_length=64)),
                ("external_mappings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"verbose_name": "索引构建", "verbose_name_plural": "索引构建", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_label", models.CharField(max_length=120)),
                ("status", models.CharField(choices=[("draft", "草稿"), ("processing", "解析中"), ("review", "待复核"), ("ready", "可构建索引"), ("failed", "失败"), ("published", "已发布")], default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_contract_versions", to=settings.AUTH_USER_MODEL)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="contract_intelligence.document")),
            ],
            options={"verbose_name": "不可变文档版本", "verbose_name_plural": "不可变文档版本", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="IndexBuildDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contract_intelligence.documentversion")),
                ("index_build", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contract_intelligence.indexbuild")),
            ],
            options={"verbose_name": "索引文档快照", "verbose_name_plural": "索引文档快照"},
        ),
        migrations.AddField(model_name="indexbuild", name="document_versions", field=models.ManyToManyField(related_name="index_builds", through="contract_intelligence.IndexBuildDocument", to="contract_intelligence.documentversion")),
        migrations.CreateModel(
            name="KnowledgeProject",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_index_build", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="published_by_projects", to="contract_intelligence.indexbuild")),
            ],
            options={"verbose_name": "知识库项目", "verbose_name_plural": "知识库项目", "ordering": ("name",)},
        ),
        migrations.AddField(model_name="indexbuild", name="project", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="index_builds", to="contract_intelligence.knowledgeproject")),
        migrations.AddField(model_name="document", name="project", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="contract_intelligence.knowledgeproject")),
        migrations.CreateModel(
            name="ParserRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_name", models.CharField(max_length=100)),
                ("provider_version", models.CharField(max_length=100)),
                ("config", models.JSONField(default=dict)),
                ("config_sha256", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("running", "运行中"), ("succeeded", "成功"), ("failed", "失败")], max_length=20)),
                ("metadata", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("document_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="parser_runs", to="contract_intelligence.documentversion")),
            ],
            options={"verbose_name": "解析运行", "verbose_name_plural": "解析运行", "ordering": ("-started_at",)},
        ),
        migrations.AddField(model_name="indexbuilddocument", name="parser_run", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contract_intelligence.parserrun")),
        migrations.CreateModel(
            name="EvidenceUnit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("evidence_id", models.CharField(db_index=True, max_length=67)),
                ("kind", models.CharField(max_length=50)),
                ("ordinal", models.PositiveIntegerField()),
                ("structural_path", models.JSONField(default=list)),
                ("title_path", models.JSONField(default=list)),
                ("clause_ref", models.CharField(blank=True, max_length=100, null=True)),
                ("source_anchor", models.JSONField()),
                ("page_physical", models.PositiveIntegerField(blank=True, null=True)),
                ("page_printed", models.CharField(blank=True, max_length=50, null=True)),
                ("text", models.TextField()),
                ("normalized_text", models.TextField()),
                ("context_prefix", models.TextField(blank=True)),
                ("content_sha256", models.CharField(max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidence_units", to="contract_intelligence.documentversion")),
                ("parser_run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidence_units", to="contract_intelligence.parserrun")),
            ],
            options={"verbose_name": "证据单元", "verbose_name_plural": "证据单元", "ordering": ("parser_run", "ordinal")},
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("admin", "管理员"), ("query", "仅查询")], default="query", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="contract_intelligence.knowledgeproject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contract_project_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "项目成员", "verbose_name_plural": "项目成员"},
        ),
        migrations.CreateModel(
            name="RetrievalUnit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("retrieval_id", models.CharField(max_length=67, unique=True)),
                ("retrieval_text", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("evidence", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_unit", to="contract_intelligence.evidenceunit")),
            ],
            options={"verbose_name": "检索单元", "verbose_name_plural": "检索单元", "ordering": ("evidence__ordinal",)},
        ),
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("structured_source", "结构化原件"), ("executed_copy", "正式 PDF"), ("attachment", "附件"), ("derived_render", "系统渲染快照")], max_length=30)),
                ("file", models.FileField(max_length=500, upload_to=walkie_dokie.contract_intelligence.models.source_upload_path)),
                ("original_name", models.CharField(editable=False, max_length=300)),
                ("mime_type", models.CharField(blank=True, max_length=150)),
                ("sha256", models.CharField(db_index=True, editable=False, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="source_files", to="contract_intelligence.documentversion")),
            ],
            options={"verbose_name": "源文件", "verbose_name_plural": "源文件", "ordering": ("role", "created_at")},
        ),
        migrations.AddField(model_name="parserrun", name="source_file", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="parser_runs", to="contract_intelligence.sourcefile")),
        migrations.AddField(model_name="evidenceunit", name="source_file", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidence_units", to="contract_intelligence.sourcefile")),
        migrations.CreateModel(
            name="ComparisonReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("not_run", "未运行"), ("match", "未发现实质差异"), ("warning", "需要人工复核"), ("mismatch", "检测到关键差异")], max_length=20)),
                ("summary", models.TextField()),
                ("metrics", models.JSONField(default=dict)),
                ("differences", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="comparison_reports", to="contract_intelligence.documentversion")),
                ("executed_copy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="executed_comparisons", to="contract_intelligence.sourcefile")),
                ("structured_source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="structured_comparisons", to="contract_intelligence.sourcefile")),
            ],
            options={"verbose_name": "原件/PDF 一致性报告", "verbose_name_plural": "原件/PDF 一致性报告", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="AuthorityReview",
            fields=[
                ("document_version", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name="authority_review", serialize=False, to="contract_intelligence.documentversion")),
                ("files_are_same_final_version", models.BooleanField(default=False)),
                ("reviewed_hashes", models.JSONField(default=dict, editable=False)),
                ("note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(auto_now=True)),
                ("authoritative_source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="authority_reviews", to="contract_intelligence.sourcefile")),
                ("reviewer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_authority_reviews", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "最终稿人工确认", "verbose_name_plural": "最终稿人工确认"},
        ),
        migrations.AddConstraint(model_name="documentversion", constraint=models.UniqueConstraint(fields=("document", "version_label"), name="contract_unique_document_version")),
        migrations.AddConstraint(model_name="indexbuild", constraint=models.UniqueConstraint(fields=("project", "name"), name="contract_unique_index_build_name")),
        migrations.AddConstraint(model_name="document", constraint=models.UniqueConstraint(fields=("project", "name"), name="contract_unique_document_name")),
        migrations.AddConstraint(model_name="indexbuilddocument", constraint=models.UniqueConstraint(fields=("index_build", "document_version"), name="contract_unique_build_document")),
        migrations.AddConstraint(model_name="projectmembership", constraint=models.UniqueConstraint(fields=("project", "user"), name="contract_unique_project_member")),
        migrations.AddConstraint(model_name="sourcefile", constraint=models.UniqueConstraint(condition=models.Q(("role__in", ("structured_source", "executed_copy", "derived_render"))), fields=("document_version", "role"), name="contract_one_primary_source_per_role")),
        migrations.AddConstraint(model_name="evidenceunit", constraint=models.UniqueConstraint(fields=("parser_run", "evidence_id"), name="contract_unique_run_evidence")),
    ]
