# Generated by Django 5.2.17 on 2026-08-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract_intelligence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrievalTrace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("query", models.TextField()),
                ("provider_name", models.CharField(max_length=100)),
                ("provider_version", models.CharField(max_length=100)),
                ("parameters", models.JSONField(default=dict)),
                ("query_tokens", models.JSONField(default=list)),
                ("candidates", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contract_retrieval_traces", to=settings.AUTH_USER_MODEL)),
                ("index_build", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_traces", to="contract_intelligence.indexbuild")),
                ("parser_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_traces", to="contract_intelligence.parserrun")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="retrieval_traces", to="contract_intelligence.knowledgeproject")),
            ],
            options={"verbose_name": "检索 Trace", "verbose_name_plural": "检索 Trace", "ordering": ("-created_at",)},
        )
    ]
