# Generated by Django 5.2.17 on 2026-08-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract_intelligence", "0002_retrievaltrace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform", models.CharField(default="admin", max_length=30)),
                ("actor_key_hash", models.CharField(blank=True, max_length=64)),
                ("question", models.TextField()),
                ("status", models.CharField(choices=[("running", "运行中"), ("answered", "已回答"), ("refused", "证据不足拒答"), ("clarification", "需要澄清"), ("failed", "失败")], default="running", max_length=30)),
                ("answer_payload", models.JSONField(default=dict)),
                ("workflow_trace", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("actor_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contract_question_runs", to=settings.AUTH_USER_MODEL)),
                ("index_build", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="question_runs", to="contract_intelligence.indexbuild")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="question_runs", to="contract_intelligence.knowledgeproject")),
            ],
            options={"verbose_name": "合同问答运行", "verbose_name_plural": "合同问答运行", "ordering": ("-started_at",)},
        )
    ]
