# Generated by Django 5.2.17 on 2026-08-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract_intelligence", "0003_questionrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceMappingSpec",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("sheet_name", models.CharField(max_length=200)),
                ("header_row", models.PositiveIntegerField(default=1)),
                ("data_start_row", models.PositiveIntegerField(default=2)),
                ("data_end_row", models.PositiveIntegerField(blank=True, null=True)),
                ("field_columns", models.JSONField(help_text='受支持字段到 Excel 列字母，例如 {"product_name":"A","unit_price":"D","currency":"E"}')),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_price_mapping_specs", to=settings.AUTH_USER_MODEL)),
                ("document_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="price_mapping_specs", to="contract_intelligence.documentversion")),
                ("source_file", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="price_mapping_specs", to="contract_intelligence.sourcefile")),
            ],
            options={"verbose_name": "价目表 MappingSpec", "verbose_name_plural": "价目表 MappingSpec", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="PriceImportRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("running", "运行中"), ("succeeded", "成功"), ("failed", "失败")], max_length=20)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("rejected_rows", models.JSONField(default=list)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("mapping_spec", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="import_runs", to="contract_intelligence.pricemappingspec")),
            ],
            options={"verbose_name": "价格导入运行", "verbose_name_plural": "价格导入运行", "ordering": ("-started_at",)},
        ),
        migrations.CreateModel(
            name="PriceRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("staging", "待人工确认"), ("trusted", "可信"), ("rejected", "已拒绝")], default="staging", max_length=20)),
                ("product_code", models.CharField(blank=True, max_length=200)),
                ("product_name", models.CharField(max_length=500)),
                ("region", models.CharField(blank=True, max_length=200)),
                ("customer", models.CharField(blank=True, max_length=200)),
                ("channel", models.CharField(blank=True, max_length=200)),
                ("price_kind", models.CharField(blank=True, max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=8, max_digits=30)),
                ("currency", models.CharField(blank=True, max_length=20)),
                ("unit", models.CharField(blank=True, max_length=100)),
                ("tax_included", models.BooleanField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("minimum_quantity", models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ("maximum_quantity", models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ("notes", models.TextField(blank=True)),
                ("extensions", models.JSONField(default=dict)),
                ("source_sheet", models.CharField(max_length=200)),
                ("source_row", models.PositiveIntegerField()),
                ("source_cells", models.JSONField(default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="price_records", to="contract_intelligence.documentversion")),
                ("header_evidence", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="price_header_records", to="contract_intelligence.evidenceunit")),
                ("import_run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="price_records", to="contract_intelligence.priceimportrun")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_price_records", to=settings.AUTH_USER_MODEL)),
                ("row_evidence", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="price_row_records", to="contract_intelligence.evidenceunit")),
            ],
            options={"verbose_name": "结构化价格记录", "verbose_name_plural": "结构化价格记录", "ordering": ("product_name", "region", "valid_from")},
        ),
        migrations.AddConstraint(model_name="pricemappingspec", constraint=models.UniqueConstraint(fields=("document_version", "name", "version"), name="contract_unique_price_mapping_version")),
        migrations.AddIndex(model_name="pricerecord", index=models.Index(fields=["document_version", "status", "product_code"], name="contract_in_documen_84aa44_idx")),
        migrations.AddIndex(model_name="pricerecord", index=models.Index(fields=["document_version", "status", "product_name"], name="contract_in_documen_5dcd2f_idx")),
        migrations.AddConstraint(model_name="pricerecord", constraint=models.UniqueConstraint(fields=("import_run", "source_sheet", "source_row"), name="contract_unique_price_import_row")),
    ]
