# Generated by Django 5.2.17 on 2026-08-13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract_intelligence", "0004_pricemappingspec_priceimportrun_pricerecord_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalProjectBinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform", models.CharField(default="feishu", max_length=30)),
                ("subject_type", models.CharField(choices=[("user", "私聊用户"), ("chat", "群聊")], max_length=20)),
                ("subject_id", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("is_selected", models.BooleanField(default=False, help_text="私聊用户可绑定多个项目，但同时只能选择一个；群聊固定项目必须勾选。")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="external_bindings", to="contract_intelligence.knowledgeproject")),
            ],
            options={
                "verbose_name": "飞书项目绑定",
                "verbose_name_plural": "飞书项目绑定",
                "constraints": [
                    models.UniqueConstraint(fields=("platform", "subject_type", "subject_id", "project"), name="contract_unique_external_project_binding"),
                    models.UniqueConstraint(condition=models.Q(("is_active", True), ("is_selected", True)), fields=("platform", "subject_type", "subject_id"), name="contract_one_selected_external_project"),
                ],
            },
        )
    ]
