# Generated by Django 5.2.17 on 2026-08-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract_intelligence", "0005_externalprojectbinding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("running", "运行中"), ("succeeded", "成功"), ("failed", "失败")], max_length=20)),
                ("provider_configuration", models.JSONField(default=dict)),
                ("metrics", models.JSONField(default=dict)),
                ("case_results", models.JSONField(default=list)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("index_build", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_runs", to="contract_intelligence.indexbuild")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_runs", to="contract_intelligence.knowledgeproject")),
            ],
            options={"verbose_name": "评估运行", "verbose_name_plural": "评估运行", "ordering": ("-started_at",)},
        ),
        migrations.CreateModel(
            name="GoldenCase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("expected_status", models.CharField(choices=[("answered", "应回答"), ("refused", "应拒答"), ("clarification", "应澄清")], max_length=30)),
                ("expected_evidence_ids", models.JSONField(default=list)),
                ("expected_answer_contains", models.JSONField(default=list, help_text="回答必须包含的人工确认事实片段；不是完整标准话术。")),
                ("expected_calculation_result", models.CharField(blank=True, max_length=200)),
                ("tags", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("index_build", models.ForeignKey(blank=True, help_text="为空时评估当前 Published IndexBuild；固定后用于历史复现。", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="golden_cases", to="contract_intelligence.indexbuild")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="golden_cases", to="contract_intelligence.knowledgeproject")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_golden_cases", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Golden QA", "verbose_name_plural": "Golden QA", "ordering": ("project", "created_at")},
        ),
    ]
